### PR TITLE
Create it_it.json

### PR DESCRIPTION
**Pull request by FoxWorn3365**

### CODE REVIEW

**Review by FoxWorn3365 — COMMENTED** [review]
IT

**Comment by jason-bowen-zheng** [comment]
Which language?

**Comment by jason-bowen-zheng** [comment]
Italian?

**Comment by FoxWorn3365** [comment]
Yes, I'm Italian

Il Lun 4 Ott 2021, 08:56 郑博文 ***@***.***> ha scritto:

**Comment by jason-bowen-zheng** [comment]
Thanks for your contribute, I'll check it before merge it.

**Comment by jason-bowen-zheng** [comment]
`Superpiatto` means `superflat`(**超**平坦)?

**Comment by FoxWorn3365** [comment]
Yes

Il Lun 4 Ott 2021, 12:14 郑博文 ***@***.***> ha scritto:

**Comment by jason-bowen-zheng** [comment]
It's a bit strange in Chinese and English

**Comment by FoxWorn3365** [comment]
Italian is very very difficult and complex 😕
And Google Translate don't work good with Italian

Il Lun 4 Ott 2021, 13:08 郑博文 ***@***.***> ha scritto:

**Comment by jason-bowen-zheng** [comment]
OK, I'll merge your change, and someone in the future will update it.

**Pull request merged**
